name: weather_today
description: A weather app demo with animation and dark theme
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.2
  provider: ^6.1.5
  lottie: ^3.1.0
  intl: ^0.18.1
  fl_chart: ^0.66.0
  vnlunar: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
